return {
  -- name: models-name
  s("models-name", {
    t(" models_name = ["),
    t("    # ─── MICRO: <500MB (bajo 1GB RAM) ───"),
    t("    {"),
    t("        \"name\": \"Qwen/Qwen2.5-0.5B-Instruct\","),
    t("        \"size\": \"~400MB (Q4)\","),
    t("        \"params\": \"0.5B\","),
    t("        \"ram\": \"~1GB\","),
    t("        \"use_case\": \"Tareas simples,-chat rápido, offline\","),
    t("        \"highlights\": \"Mejor en su clase sub-1B, 29+ idiomas, contexto 32K\","),
    t("        \"quantized_gguf\": \"jc-builds/Qwen2.5-0.5B-Instruct-Q4_K_M-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"microsoft/Phi-3-mini-4k-instruct\","),
    t("        \"size\": \"~800MB (Q4)\","),
    t("        \"params\": \"3.8B\","),
    t("        \"ram\": \"~1.5GB\","),
    t("        \"use_case\": \"Código simple, razonamiento básico\","),
    t("        \"highlights\": \"Muy eficiente, buena calidad para su tamaño\","),
    t("        \"quantized_gguf\": \"TheBloke/Phi-3-mini-4k-instruct-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"google/gemma-2b-it\","),
    t("        \"size\": \"~1.7GB (Q4)\","),
    t("        \"params\": \"2B\","),
    t("        \"ram\": \"~2GB\","),
    t("        \"use_case\": \"Chat general, completado de texto\","),
    t("        \"highlights\": \"Modelo de Google, buena calidad conversacional\","),
    t("        \"quantized_gguf\": \"TheBloke/gemma-2b-it-GGUF\","),
    t("    },"),
    t(""),
    t("    # ─── SMALL: 500MB–2GB ───"),
    t("    {"),
    t("        \"name\": \"Qwen/Qwen2.5-1.5B-Instruct\","),
    t("        \"size\": \"~1GB (Q4)\","),
    t("        \"params\": \"1.5B\","),
    t("        \"ram\": \"~1.5GB\","),
    t("        \"use_case\": \"Chat, resumen, traducción ligera\","),
    t("        \"highlights\": \"Excelente relación calidad/tamaño, 32K contexto\","),
    t("        \"quantized_gguf\": \"Qwen/Qwen2.5-1.5B-Instruct-Q4_K_M-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"unsloth/Llama-3.2-1B-Instruct\","),
    t("        \"size\": \"~900MB (Q4)\","),
    t("        \"params\": \"1B\","),
    t("        \"ram\": \"~1.2GB\","),
    t("        \"use_case\": \"Asistente general, respuesta rápida\","),
    t("        \"highlights\": \"Optimizado con Unsloth, ultrarrápido en GPU\","),
    t("        \"quantized_gguf\": None,"),
    t("    },"),
    t("    {"),
    t("        \"name\": \"meta-llama/Llama-3.2-3B-Instruct\","),
    t("        \"size\": \"~1.9GB (Q4)\","),
    t("        \"params\": \"3B\","),
    t("        \"ram\": \"~2.5GB\","),
    t("        \"use_case\": \"Mejor calidad en rango pequeño, razonamiento\","),
    t("        \"highlights\": \"68% compresión con Q4_K_M, 61.8 MMLU\","),
    t("        \"quantized_gguf\": \"TheBloke/Llama-3.2-3B-Instruct-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"Daemontatox/Droidz\","),
    t("        \"size\": \"~1.7GB\","),
    t("        \"params\": \"1.7B\","),
    t("        \"ram\": \"~3.6GB (Mac M2)\","),
    t("        \"use_case\": \"Edge, razonamiento reflexivo, agents\","),
    t("        \"highlights\": \"23 tok/s en Mac M2, self-verification, Apache 2.0\","),
    t("        \"quantized_gguf\": \"Daemontatox/Droidz-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"Qwen/Qwen3-1.7B\","),
    t("        \"size\": \"~1GB (Q4 ONNX)\","),
    t("        \"params\": \"1.7B\","),
    t("        \"ram\": \"~1.3GB\","),
    t("        \"use_case\": \"Android mid-range, edge computing\","),
    t("        \"highlights\": \"~10 tok/s en Dimensity 6300, optimizado XNNPACK\","),
    t("        \"quantized_gguf\": \"Edison2ST/Qwen3-1.7B-Q4-ONNX\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"NexaAI/LFM2.5-1.2B-mobile\","),
    t("        \"size\": \"~1.2GB\","),
    t("        \"params\": \"1.2B\","),
    t("        \"ram\": \"~1.5GB\","),
    t("        \"use_case\": \"Mobile NPU (Snapdragon 8 Gen 4), IoT\","),
    t("        \"highlights\": \"Optimizado para NPU Qualcomm, offline total\","),
    t("        \"quantized_gguf\": None,"),
    t("    },"),
    t(""),
    t("    # ─── MEDIUM: 2GB–4GB ───"),
    t("    {"),
    t("        \"name\": \"Qwen/Qwen2.5-3B-Instruct\","),
    t("        \"size\": \"~2GB (Q4)\","),
    t("        \"params\": \"3B\","),
    t("        \"ram\": \"~2.5GB\","),
    t("        \"use_case\": \"Mejor equilibrio, tareas complejas\","),
    t("        \"highlights\": \"32K contexto, buena calidad multilenguaje\","),
    t("        \"quantized_gguf\": \"TheBloke/Qwen2.5-3B-Instruct-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"microsoft/Phi-3.5-mini-instruct\","),
    t("        \"size\": \"~2.3GB (Q4)\","),
    t("        \"params\": \"3.8B\","),
    t("        \"ram\": \"~2.5GB\","),
    t("        \"use_case\": \"Código, análisis, herramientas\","),
    t("        \"highlights\": \"Soporte de tools/function calling\","),
    t("        \"quantized_gguf\": \"TheBloke/Phi-3.5-mini-instruct-GGUF\","),
    t("    },"),
    t(""),
    t("    # ─── LARGE: 4GB+ (solo tablets/high-end) ───"),
    t("    {"),
    t("        \"name\": \"mistralai/Mistral-7B-Instruct-v0.3\","),
    t("        \"size\": \"~4.1GB (Q4)\","),
    t("        \"params\": \"7B\","),
    t("        \"ram\": \"~5GB\","),
    t("        \"use_case\": \"Tablet con 8GB+ VRAM, tareas pesadas\","),
    t("        \"highlights\": \"62.5 MMLU, referencia en calidad/velocidad\","),
    t("        \"quantized_gguf\": \"TheBloke/Mistral-7B-Instruct-v0.3-GGUF\","),
    t("    },"),
    t("    {"),
    t("        \"name\": \"google/gemma-2-9b-it\","),
    t("        \"size\": \"~5GB (Q4)\","),
    t("        \"params\": \"9B\","),
    t("        \"ram\": \"~6GB\","),
    t("        \"use_case\": \"Alta calidad, necesita GPU dedicado\","),
    t("        \"highlights\": \"Mejor calidad de Google, 9B params\","),
    t("        \"quantized_gguf\": \"TheBloke/gemma-2-9b-it-GGUF\","),
    t("    },"),
    t("]")
  }),
}
